[package]
name = "taxutils-python"
version = "1.1.1"
edition = "2021"
publish = false

[lib]
name = "taxutils_rust"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
pyo3 = { version = "0.23.5", features = ["abi3-py310", "extension-module"] }
taxutils-core = { package = "taxutils", version = ">=1.1.1, <2" }
